image: gitpod/workspace-mongodb

tasks:
  - name: Run database
    command: mongod
  - name: Run back-end
    init: |
      cd server
      npm install
    command: |
      node seed-db.js
      node index.js
ports:
  - name: back-end
    port: 8080
    onOpen: ignore
    visibility: public
