image: gitpod/workspace-mongodb

tasks:
  - name: Run database
    command: mongod
  - name: Run back-end
    init: |
      cd server
      npm install
      node seed-db.js
    command: npm run start
ports:
  - name: back-end
    port: 8080
    onOpen: ignore
    visibility: public
