image: gitpod/workspace-mongodb

tasks:
  - name: run back-end
    command: |
      cd server
      npm install
      npm run start
ports:
  - name: back-end
    port: 8080
    onOpen: ignore
  - name: database
    port: 27017
    onOpen: ignore
