image: gitpod/workspace-mongodb

tasks:
  - name: MongoDB
    command: mongod
  - name: Run Node.js server
    init: |
      cd server
      npm install
    command: |
      cd server
      node seed-db-gitpod.js
      node index-gitpod.js
  - name: React admin panel
    init: |
      cd admin-gitpod
      npm install
    command: |
      cd admin-gitpod
      npm run dev
  - name: OpenAPI folder
    init: |
      cd openapi
      npm install
    command: |
      cd openapi
      if [ ! -f openapi.yml ]; then
        echo "openapi.yml does not exist. Creating a copy from openapi.original.yml..."
        cp openapi.original.yml openapi.yml || { echo "Failed to copy openapi.original.yml"; exit 1; }
        node wipeOpenApiDescription.js
      else
        echo "openapi.yml already exists. Exiting script."
        exit 0
      fi
ports:
  - name: Node.js server
    port: 8080
    # swagger ui docs tied to server:
    # http://localhost:8080/docs
    onOpen: ignore
    visibility: public
  - name: React admin panel
    port: 5173
    onOpen: open-browser
    visibility: public
