sequenceDiagram
    participant User
    participant  Client
    participant API

    User->> Client: Sign up with email, password, username
    Client->>API: POST /users (account creation)
    API-->> Client: 201 Created

    User->> Client: Log in with username and password
    Client->>API: POST /auth/token (User Login)
    API-->> Client: Response (access_token, refresh_token, expires_at)

    User->> Client: Access protected endpoints with access_token
    Client->>API: Make authorized request
    API-->> Client: Validated response (based on access_token)

    Note over User, API: Access token expires
    User->> Client: Request new access token using refresh_token
    Client->>API: POST /auth/refresh-token
    API-->> Client: Response (new access_token, refresh_token)