sequenceDiagram
    %% Placing Order
    participant Patron as Patron
    participant Client as Client
    participant API as API

    Patron->>Client: Add dishes to order
    Patron->>Client: View bill
    Client->>API: GET /orders/{id}/dishes
    API->>Client: 200 OK, total_results: 5

    Patron->>Client: Place order
    Client->>API: POST /orders
    API->>Client: 201 Created

    Client->>Patron: Order confirmation
