sequenceDiagram
    %% Checking Preparation Times and Updating Order Priority
    participant Staff as Staff
    participant Client as API Client
    participant API as API

    loop Check dish preparation times
        Client->>API: GET /dishes/{id}?fields=preparation_time
        API->>Client: 200 OK, preparation_time: 15 mins
    end

    Staff->>Client: Update order priority
    Client->>API: PUT /orders/{order_id} Data: { "priority": 1, "status": "Received" }
    API->>Client: 200 OK, Order updated
