journey
    title Staff user journey - Tableside vs. Takeaway delivery
      section Table-side Delivery
        Update Order Status to On the Way: 5: Expeditor
        Deliver Order to Table: 5: Food runner
      section Takeaway Delivery
        Bring Order to Pickup Station: 5: Expeditor
        Update Status to Ready for Pickup: 5: Expeditor
        Patron Picks Up Order: 5: Patron