journey
    title Staff User Journey - Order Fulfillment
    section Receive Order
      Prioritization: 5: Expeditor
      Initiate Preparation: 5: Expeditor
    section Preparation
      Preparation: 5: Station
      Station Completion: 5: Station
      Assemble order: 5: Expeditor